services:
  postgres:
    image: postgres:15
    container_name: postgres_quarkus_social
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"